"""Paragraph - Added Act rel

Revision ID: 0517b02c356c
Revises: 184c4c858fdb
Create Date: 2025-05-02 14:40:56.642081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0517b02c356c'
down_revision: Union[str, None] = '184c4c858fdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paragraphs', sa.Column('act_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'paragraphs', 'acts', ['act_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paragraphs', type_='foreignkey')
    op.drop_column('paragraphs', 'act_id')
    # ### end Alembic commands ###
