"""Faction relationships fix #2

Revision ID: 0f0bf0251de4
Revises: 73fc8273e187
Create Date: 2025-04-23 12:36:20.654186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f0bf0251de4'
down_revision: Union[str, None] = '73fc8273e187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faction_relationships', sa.Column('faction_a_id', sa.UUID(), nullable=False))
    op.add_column('faction_relationships', sa.Column('faction_b_id', sa.UUID(), nullable=False))
    op.add_column('faction_relationships', sa.Column('event_act_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'faction_relationships', 'factions', ['faction_a_id'], ['id'])
    op.create_foreign_key(None, 'faction_relationships', 'acts', ['event_act_id'], ['id'])
    op.create_foreign_key(None, 'faction_relationships', 'factions', ['faction_b_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'faction_relationships', type_='foreignkey')
    op.drop_constraint(None, 'faction_relationships', type_='foreignkey')
    op.drop_constraint(None, 'faction_relationships', type_='foreignkey')
    op.drop_column('faction_relationships', 'event_act_id')
    op.drop_column('faction_relationships', 'faction_b_id')
    op.drop_column('faction_relationships', 'faction_a_id')
    # ### end Alembic commands ###
