"""Character relationships model - fix #2

Revision ID: 27c9e63db880
Revises: e4b1fbd7c7ab
Create Date: 2025-04-25 13:16:18.204971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27c9e63db880'
down_revision: Union[str, None] = 'e4b1fbd7c7ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_relationships', sa.Column('character_a_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'character_trait', 'characters', ['character_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'character_trait', type_='foreignkey')
    op.drop_column('character_relationships', 'character_a_id')
    # ### end Alembic commands ###
