"""Beat - Added Project relationship

Revision ID: 3034c6f4a24b
Revises: a1226f8737cd
Create Date: 2025-04-23 17:35:23.323687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3034c6f4a24b'
down_revision: Union[str, None] = 'a1226f8737cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beats', sa.Column('project_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'beats', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'beats', type_='foreignkey')
    op.drop_column('beats', 'project_id')
    # ### end Alembic commands ###
