"""Character relationships model

Revision ID: 3d7bf27b4f9c
Revises: 9d585589b59f
Create Date: 2025-04-25 12:47:04.641806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d7bf27b4f9c'
down_revision: Union[str, None] = '9d585589b59f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_b_id', sa.UUID(), nullable=False),
    sa.Column('event_date', sa.String(), nullable=True),
    sa.Column('act_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['act_id'], ['acts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_relationships')
    # ### end Alembic commands ###
