"""Character relationships model - fix #3

Revision ID: 497a2d4b2cd3
Revises: 27c9e63db880
Create Date: 2025-04-25 16:24:08.224253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '497a2d4b2cd3'
down_revision: Union[str, None] = '27c9e63db880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('character_relationships', 'act_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('character_relationships', 'act_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
