"""Project - Extended metadata

Revision ID: 99c40f8f0112
Revises: ab7ae447ea11
Create Date: 2025-05-01 13:14:14.459619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99c40f8f0112'
down_revision: Union[str, None] = 'ab7ae447ea11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('time_period', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('audience', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('setting', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'setting')
    op.drop_column('projects', 'audience')
    op.drop_column('projects', 'time_period')
    # ### end Alembic commands ###
