"""Trait - Label will be optional

Revision ID: 9d585589b59f
Revises: e6f1ed90e76c
Create Date: 2025-04-25 11:49:19.676202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d585589b59f'
down_revision: Union[str, None] = 'e6f1ed90e76c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('character_trait', 'label',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('character_trait', 'label',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
