"""Faction relationships fix #4

Revision ID: a1226f8737cd
Revises: f7b7c76fae60
Create Date: 2025-04-23 12:51:02.190553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1226f8737cd'
down_revision: Union[str, None] = 'f7b7c76fae60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('faction_relationships_faction_b_id_fkey', 'faction_relationships', type_='foreignkey')
    op.drop_constraint('faction_relationships_faction_a_id_fkey', 'faction_relationships', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('faction_relationships_faction_a_id_fkey', 'faction_relationships', 'factions', ['faction_a_id'], ['id'])
    op.create_foreign_key('faction_relationships_faction_b_id_fkey', 'faction_relationships', 'factions', ['faction_b_id'], ['id'])
    # ### end Alembic commands ###
