"""Scene - Act column to UUID #2

Revision ID: ab7ae447ea11
Revises: 497a2d4b2cd3
Create Date: 2025-04-30 10:33:44.809504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab7ae447ea11'
down_revision: Union[str, None] = '497a2d4b2cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenes', sa.Column('act_id', sa.UUID(), nullable=True))
    op.drop_column('scenes', 'act')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenes', sa.Column('act', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('scenes', 'act_id')
    # ### end Alembic commands ###
