"""Character relationships model - fix #1

Revision ID: e4b1fbd7c7ab
Revises: 3d7bf27b4f9c
Create Date: 2025-04-25 13:15:17.926382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4b1fbd7c7ab'
down_revision: Union[str, None] = '3d7bf27b4f9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_relationships', sa.Column('description', sa.String(), nullable=False))
    op.alter_column('character_relationships', 'relationship_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('character_trait_character_id_fkey', 'character_trait', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('character_trait_character_id_fkey', 'character_trait', 'characters', ['character_id'], ['id'])
    op.alter_column('character_relationships', 'relationship_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('character_relationships', 'description')
    # ### end Alembic commands ###
