"""Autogenerate last two revisions

Revision ID: edb097709bde
Revises: 9a29030d70a4
Create Date: 2025-04-20 20:11:22.554926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edb097709bde'
down_revision: Union[str, None] = '9a29030d70a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beats', sa.Column('paragraph_id', sa.UUID(), nullable=True))
    op.add_column('beats', sa.Column('paragraph_title', sa.String(), nullable=True))
    op.add_column('beats', sa.Column('completed', sa.Boolean(), nullable=True))
    op.drop_column('beats', 'status')
    op.add_column('characters', sa.Column('body_url', sa.String(), nullable=True))
    op.add_column('characters', sa.Column('transparent_body_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'transparent_body_url')
    op.drop_column('characters', 'body_url')
    op.add_column('beats', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('beats', 'completed')
    op.drop_column('beats', 'paragraph_title')
    op.drop_column('beats', 'paragraph_id')
    # ### end Alembic commands ###
